name = "sonagi-anvil"
compatibility_date = "2024-06-29"

# [Pages] 배포 디렉토리 설정
pages_build_output_dir = "public"

# [D1] 훈련 기록 저장용 Database 바인딩
[[d1_databases]]
binding = "DB"
database_name = "anvil-records"
database_id = "00257268-799d-4cc8-a904-8f15f9ebd7ac"
